### PR TITLE
fix: use placeholder image when item image is missing

### PR DESCRIPTION
**Pull request by aclementev**
# Description

Use placeholder image when displaying an Item without a set image.

image

### CODE REVIEW

**Comment by vanessa-cooper** [comment]
Thanks @alvaroclementev, I'll review the changes right away!

**Review by vanessa-cooper — CHANGES_REQUESTED** [review]
Make sure all checks pass, only then you can merge the PR.

**Comment by aclementev** [comment]
This fixes #4

**Review by vanessa-cooper — APPROVED** [review]
Excellent job @alvaroclementev! You're now able to merge the PR.

**Pull request merged**
